name: Terraform Plan and Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: c489150e-3908-420e-821b-5b4307f1e620
      ARM_CLIENT_SECRET: xbJ8Q~LqcwykHBP43VXgkmDA6Ia1G5utqMd~cbA8
      ARM_SUBSCRIPTION_ID: 069f9a67-70d9-4dc5-9e4a-b3e56d0d80af

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        run: az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_SUBSCRIPTION_ID

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
